logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:mem:books

  flyway:
    enabled: true

  data:
    mongodb:
      host: localhost
      database: asp_library

