version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=library
      - LOGGING_LEVEL_ROOT=ERROR
    container_name: api
    networks:
      - nw
  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
      - "8081:27017"
    networks:
      - nw
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - nw
networks:
  nw: