logging:
  level:
    root: INFO
spring:
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      port: 0
      database: books
    rest:
      basePath: /api
mongock:
  change-logs-scan-package:
    - ru.otus.homework.popov.hw16.mongock.changelog