logging:
  level:
    root: ERROR
    org:
      springframework:
        security: ERROR
spring:
  mongodb:
    embedded:
      version: 3.5.5

  data:
    mongodb:
      port: 27017
      database: books

mongock:
  change-logs-scan-package:
    - ru.otus.homework.popov.mongock.changelog