logging:
  level:
    root: WARN

spring:
  messages:
    basename: i18n/messages

application:
  locale: ru-RU
  #locale: es-ES
  #no locale -> english

  questionsBaseName: questions/questions
  scoreToPass: 3